import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from '@chakra-ui/react';
import { AuthProvider } from '@/feature/auth/AuthProvider';
import { Header } from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <AuthProvider>
        <ChakraProvider>
          <body className={inter.className}>
            <Header />
            <section className="inner">{children}</section>
          </body>
        </ChakraProvider>
      </AuthProvider>
    </html>
  );
}
